In [1]:
%matplotlib inline
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import py2neo as pn
from py2neo import *
import ClassProtGraph as mg


In [2]:
pn.authenticate("localhost:7474", "neo4j", "pxyon123")
dbGraph = pn.Graph()


In [3]:
pdbSym1 = '2JKU'
gProt1 = mg.ClassProtGraph(dbGraph, pdbSym1)
gProt1.number_of_nodes()

35

In [4]:
gProt1.graphNumber(k=2)

array([0.36090153, 0.39389482])

In [5]:
pdbSym2 = '1HF9'
gProt2 = mg.ClassProtGraph(dbGraph, pdbSym2)
gProt2.number_of_nodes()

41

In [10]:
gProt2.graphNumber(k=2)

array([0.31051649, 0.34440739])

In [11]:
gProt1.RavettiDissimilarity(gProt2)

0.07343672578122211

In [12]:
gProt2.RavettiDissimilarity(gProt1)

0.07343672578122211

In [13]:
pdbSym3 = '3PC7'
gProt3 = mg.ClassProtGraph(dbGraph, pdbSym3)
gProt3.number_of_nodes()

80

In [14]:
gProt3.graphNumber(k=2)

array([0.31996602, 0.34806294])